export const ROUTES = {
    HOME: "/",
    PRODUCT: `/products`,
    CHECKOUT: "/checkout",
    CONTACT: "/contact-us",
    TERMS: "/terms",
    POLICY: "/privacy",
    FAQ: "/faq",
    FORGET_PASSWORD: "/forget-password",
    ACCOUNT: "/my-account",
    ORDERS: "/my-account/orders",
    ACCOUNT_DETAILS: "/my-account/AccountDetail",
    CHANGE_PASSWORD: "/my-account/ChangePassword",
    SHOPS: "/shops",
    LOGIN: "/signin",
    SIGN_UP: "/signup",
    SEARCH: "/search",
    COLLECTIONS: "/collections",
    CATEGORY: "/category",
    ORDER: "/order",
    PRODUCT_REGISTER: "/my-account/ProductRegister",
};
